### ISSUE TITLE
Style PlantPage and Add Remove Plant Functionality

### ISSUE THREAD

**Issue by ccatherinetan** [calblueprint/trap-garden#49]
https://linear.app/trap-garden/issue/TG-42/style-plantpage-and-add-remove-plant-functionality

remember to git checkout main → git pull → git checkout -b [thisbranch]
* assigned: Monday 11/18
* due (PR open by): Sunday 11/24 
* MERGE by: Sunday 12/1

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the PlantCard component to include an add/remove button based on the canSelect prop. Updated styling to match existing files.

You can review changes in this commit: https://github.com/lattaai13/calblueprint-trap-garden-49/commit/3c90b5b624efe116d2b43d1562b0576ccc9c1e44.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
